[package]
authors = ["Bas Dirks"]
name = "typescript"
version = "0.1.0"
edition = "2021"

[dependencies]
ir = { path = "../ir" }
printer = { path = "../printer" }
token-set = { path = "../token-set" }
ord-str-map = { path = "../ord-str-map" }

[lib]