doc_comment_code_block_width = 80
fn_args_layout = "Vertical"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "One"
imports_granularity = "One"
imports_layout = "Vertical"
max_width = 80
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true