[package]
authors = ["Bas Dirks"]
name = "graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
print = { path = "../print" }
ir = { path = "../ir" }
token-set = { path = "../token-set" }
ord-str-map = { path = "../ord-str-map" }

[lib]